spring:
  application:
    name: finance-app
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5572}/${DB_NAME:finance}
    username: ${DB_USER:admin}
    password: ${DB_PASSWORD:admin12345}

  liquibase:
    enabled: true
    change-log: "classpath:/changelog/master.xml"
    driver-class-name: org.postgresql.Driver
    contexts: dev

server:
  port: 9069
